import { isPortfolioDemoData, getStorageKeys } from '../config/branding';
import { PORTFOLIO_SAMPLE_MARKERS } from '../data/portfolio/markers';
import { ITINERARY_MARKERS } from '../data/itineraryMarkers';

export const MARKER_TYPES = {
  spot: {
    key: 'spot',
    label: '足迹',
    labelEn: 'Footprint',
    color: '#1E88E5',
    icon: '📍',
    description: '出生地、工作地、访问地点',
    filterHint: '出生地、工作地、出访城市等日常地点',
  },
  event: {
    key: 'event',
    label: '历史事件',
    labelEn: 'Event',
    color: '#D32F2F',
    icon: '⭐',
    description: '重要历史时刻',
    filterHint: '影响较大的历史节点，如「中共十四大」',
  },
  inscription: {
    key: 'inscription',
    label: '题字',
    labelEn: 'Inscription',
    color: '#F57F17',
    icon: '✒️',
    description: '书法题字地点',
    filterHint: '书法题字所在地',
  },
};

const _sk = getStorageKeys();
export const STORAGE_KEY = _sk.markers;
export const VERSION_KEY = _sk.markersVersion;

export const DEFAULT_CENTER = [35.8617, 104.1954];
export const DEFAULT_ZOOM = 4;

const SAMPLE_MARKERS_RAW = [
  {
    id: 'spot_001',
    type: 'spot',
    name: '江苏扬州',
    latitude: 32.4007,
    longitude: 119.4278,
    country: '中国',
    province: '江苏省',
    city: '扬州市',
    date: '1926-08-17',
    title: '出生地',
    description: '出生于江苏省江都县（今扬州市），度过童年和少年时代。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方履历', note: '' }],
  },
  {
    id: 'spot_002',
    type: 'spot',
    name: '上海',
    latitude: 31.2304,
    longitude: 121.4737,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1985-06',
    title: '担任上海市市长',
    description: '1985年起任上海市市长，后任市委书记。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方履历', note: '' }],
  },
  {
    id: 'spot_003',
    type: 'spot',
    name: '北京',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1989-06',
    title: '中央工作地',
    description: '调任中央后长期在北京工作，主持中央工作',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '新华社档案', note: '' }],
  },
  {
    id: 'spot_004',
    type: 'spot',
    name: '北京',
    latitude: 39.9800,
    longitude: 116.3200,
    country: '中国',
    province: '北京市',
    city: '',
    date: '2009-04-23',
    title: '视察国机二院',
    description: '退休后视察国机二院，关心国防科技事业。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'event_001',
    type: 'event',
    name: '调任中央',
    latitude: 39.9042,
    longitude: 116.3974,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1989-05-31',
    title: '重要历史转折点',
    description: '从上海调任中央，开始新的历史阶段',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '新华社档案', note: '' }],
  },
  {
    id: 'event_002',
    type: 'event',
    name: '十三届四中全会',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1989-06-09',
    title: '十三届四中全会',
    description: '十三届四中全会召开，选举江泽民为中共中央总书记。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '党史资料', note: '' }],
  },
  {
    id: 'event_003',
    type: 'event',
    name: '南方谈话视察',
    latitude: 22.5431,
    longitude: 114.0579,
    country: '中国',
    province: '广东省',
    city: '深圳市',
    date: '1992-01-18',
    title: '南方谈话视察',
    description: '视察深圳、珠海等地，推动改革开放进入新阶段。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '人民日报档案', note: '' }],
  },
  {
    id: 'event_004',
    type: 'event',
    name: '九届全国人大一次会议',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1998-03-16',
    title: '九届全国人大一次会议',
    description: '会议选举江泽民为国家主席、国家中央军委主席。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'event_005',
    type: 'event',
    name: '澳门回归',
    latitude: 22.1987,
    longitude: 113.5439,
    country: '中国',
    province: '澳门特别行政区',
    city: '',
    date: '1999-12-20',
    title: '澳门回归祖国',
    description: '出席澳门政权交接仪式，宣布中国恢复行使主权。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '新华社', note: '' }],
  },
  {
    id: 'event_early_001',
    type: 'event',
    name: '国立中央大学',
    latitude: 32.0569,
    longitude: 118.7835,
    country: '中国',
    province: '江苏省',
    city: '南京市',
    date: '1943-09',
    title: '考入中央大学',
    description:
      '1943年自家乡考入国立（南京）中央大学电机系，后转学至国立交通大学同系。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '中央大学南京校区' }],
  },
  {
    id: 'event_early_002',
    type: 'event',
    name: '国立交通大学',
    latitude: 31.1996,
    longitude: 121.4248,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1946-04',
    title: '加入中国共产党',
    description:
      '1946年4月在上海就读国立交通大学电机系期间加入中国共产党，参与地下工作和学生运动。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '交通大学徐汇校区' }],
  },
  {
    id: 'event_early_003',
    type: 'event',
    name: '国立交通大学',
    latitude: 31.1996,
    longitude: 121.4248,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1947-07',
    title: '交大毕业',
    description: '1947年毕业于国立交通大学电机系。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_early_004',
    type: 'event',
    name: '上海',
    latitude: 31.2304,
    longitude: 121.4737,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1947-08',
    title: '上海工厂工作',
    description:
      '大学毕业后进入上海当地粮服工厂工作；新中国成立后，先后在食品、制皂、电器等行业工厂任科长、副厂长等职务。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_early_005',
    type: 'event',
    name: '第一汽车制造厂',
    latitude: 43.8436,
    longitude: 125.1445,
    country: '中国',
    province: '吉林省',
    city: '长春市',
    date: '1954-09',
    title: '参与一汽筹建',
    description: '1954年北上长春，参与第一汽车制造厂筹建工作。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '长春汽车经济技术开发区' }],
  },
  {
    id: 'event_early_006',
    type: 'event',
    name: '莫斯科',
    latitude: 55.7558,
    longitude: 37.6173,
    country: '俄罗斯',
    province: '',
    city: '莫斯科',
    date: '1955-01',
    title: '赴苏联实习',
    description: '赴苏联实习一年，回国后陆续获得提升。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_early_007',
    type: 'event',
    name: '武汉',
    latitude: 30.5928,
    longitude: 114.3055,
    country: '中国',
    province: '湖北省',
    city: '武汉市',
    date: '1962-01',
    title: '武汉研究所任职',
    description:
      '1960年代起，在第一机械工业部设于武汉等地的下属研究所担任主要领导职务。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '一机部在汉部属单位' }],
  },
  {
    id: 'event_early_008',
    type: 'event',
    name: '上海',
    latitude: 31.2304,
    longitude: 121.4737,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1965-01',
    title: '上海研究所任职',
    description:
      '1960年代起，在第一机械工业部设于上海等地的下属研究所担任主要领导职务。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '一机部在沪部属单位' }],
  },
  {
    id: 'event_early_009',
    type: 'event',
    name: '第一机械工业部',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1970-01',
    title: '调入一机部机关',
    description: '1970年被调入第一机械工业部机关工作。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '机械工业部机关·北京' }],
  },
  {
    id: 'event_early_010',
    type: 'event',
    name: '布加勒斯特',
    latitude: 44.4268,
    longitude: 26.1025,
    country: '罗马尼亚',
    province: '',
    city: '布加勒斯特',
    date: '1971-06',
    title: '援建罗马尼亚',
    description: '外派罗马尼亚，领导中国政府在当地援建项目；回国后在一机部外事局工作多年。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_career_001',
    type: 'event',
    name: '国家进出口管理委员会',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1979-01',
    title: '走上经济管理岗位',
    description:
      '改革开放后，离开技术部门，到国家进出口管理委员会工作，参与制定政策与经济特区筹建有关工作。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '国务院机关所在地·北京' }],
  },
  {
    id: 'event_career_002',
    type: 'event',
    name: '深圳经济特区',
    latitude: 22.5431,
    longitude: 114.0579,
    country: '中国',
    province: '广东省',
    city: '深圳市',
    date: '1980-08',
    title: '参与经济特区筹备',
    description:
      '在国家进出口管理委员会任职期间，参与经济特区政策制定与筹建工作（深圳、珠海、汕头、厦门等）。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_career_003',
    type: 'event',
    name: '电子工业部',
    latitude: 39.9086,
    longitude: 116.3736,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1982-05',
    title: '任电子工业部副部长',
    description: '1982年起任电子工业部副部长，后任部长。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '原电子工业部机关·北京' }],
  },
  {
    id: 'event_career_004',
    type: 'event',
    name: '中共上海市委',
    latitude: 31.2304,
    longitude: 121.4737,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1985-03',
    title: '主政上海',
    description: '1985年起任中共上海市委副书记、上海市市长，后任上海市委书记。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '中共上海市委·人民大道' }],
  },
  {
    id: 'event_career_005',
    type: 'event',
    name: '人民大会堂',
    latitude: 39.9042,
    longitude: 116.3913,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1987-11-01',
    title: '当选中央政治局委员',
    description: '在中共十三大上当选为中共中央政治局委员。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '中共十三大·北京' }],
  },
  {
    id: 'event_career_006',
    type: 'event',
    name: '中南海',
    latitude: 39.9163,
    longitude: 116.3972,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1989-11',
    title: '中共中央军委主席',
    description: '1989年11月当选为中共中央军事委员会主席。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_career_007',
    type: 'event',
    name: '全国人大',
    latitude: 39.9042,
    longitude: 116.3913,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1990-04',
    title: '国家中央军委主席',
    description: '1990年4月当选为中华人民共和国中央军事委员会主席，接替邓小平同志。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '全国人民代表大会·北京' }],
  },
  {
    id: 'event_career_008',
    type: 'event',
    name: '第八届全国人大',
    latitude: 39.9042,
    longitude: 116.3913,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1993-03-15',
    title: '当选国家主席',
    description: '在第八届全国人民代表大会第一次会议上当选为中华人民共和国主席，后连选连任。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '' }],
  },
  {
    id: 'event_career_009',
    type: 'event',
    name: '北京',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '2002-11-15',
    title: '辞去中共中央总书记',
    description: '2002年11月，不再担任中共中央总书记职务。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '中共十六大·北京' }],
  },
  {
    id: 'event_career_010',
    type: 'event',
    name: '北京',
    latitude: 39.9042,
    longitude: 116.3913,
    country: '中国',
    province: '北京市',
    city: '',
    date: '2005-03-13',
    title: '卸任全部领导职务',
    description: '2005年3月，卸任所担任的全部职务，退出领导岗位。',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '公开履历', note: '十届全国人大三次会议·北京' }],
  },
  {
    id: 'inscription_001',
    type: 'inscription',
    name: '虎门大桥',
    latitude: 22.7851,
    longitude: 113.6007,
    country: '中国',
    province: '广东省',
    city: '东莞市',
    date: '1997-06-09',
    title: '虎门大桥题字',
    description: '为虎门大桥题写桥名，标志大桥正式通车。',
    color: '#F57F17',
    icon: '✒️',
    images: [],
    sources: [{ title: '虎门大桥资料', note: '' }],
  },
  {
    id: 'inscription_002',
    type: 'inscription',
    name: '浦东图书馆',
    latitude: 31.2089,
    longitude: 121.5047,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1996-10-01',
    title: '浦东图书馆题字',
    description: '为浦东图书馆题写馆名，支持文化建设。',
    color: '#F57F17',
    icon: '✒️',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'spot_005',
    type: 'spot',
    name: '美国华盛顿',
    latitude: 38.9072,
    longitude: -77.0369,
    country: '美国',
    province: '',
    city: '华盛顿',
    date: '1997-10-26',
    title: '首次国事访美',
    description: '12年来中国国家元首首次正式访美，开启中美关系新篇章。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '新华社档案', note: '' }],
  },
  {
    id: 'spot_006',
    type: 'spot',
    name: '俄罗斯莫斯科',
    latitude: 55.7558,
    longitude: 37.6173,
    country: '俄罗斯',
    province: '',
    city: '莫斯科',
    date: '1996-04-25',
    title: '中俄战略协作伙伴',
    description: '与叶利钦会晤，签署《中俄联合声明》，深化战略伙伴关系。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'spot_007',
    type: 'spot',
    name: '瑞士日内瓦',
    latitude: 46.2044,
    longitude: 6.1432,
    country: '瑞士',
    province: '',
    city: '日内瓦',
    date: '1998-05-18',
    title: '世贸组织总部访问',
    description: '访问 WTO 总部，强调中国加入多边贸易体制的决心。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'spot_008',
    type: 'spot',
    name: '法国巴黎',
    latitude: 48.8566,
    longitude: 2.3522,
    country: '法国',
    province: '',
    city: '巴黎',
    date: '1999-10-25',
    title: '中法全面伙伴关系',
    description: '访问法国，推进中法全面战略伙伴关系。',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方新闻', note: '' }],
  },
  {
    id: 'spot_br1993_brasilia',
    type: 'spot',
    name: '巴西利亚',
    latitude: -15.7975,
    longitude: -47.8919,
    country: '巴西',
    province: '',
    city: '巴西利亚',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '1993年巴西国事访问',
    description: '在巴西利亚出席欢迎仪式及会谈，获颁「南十字座」大项链勋章。',
    tripSummary:
      '应巴西总统伊塔马尔·佛朗哥的邀请，于1993年11月22日至28日对巴西进行国事访问，先后抵达巴西利亚、伊瓜苏、圣若泽、圣保罗、里约热内卢、马瑙斯等地。',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '1993年11月' }],
  },
  {
    id: 'spot_br1993_iguacu',
    type: 'spot',
    name: '伊瓜苏',
    latitude: -25.5163,
    longitude: -54.5854,
    country: '巴西',
    province: '',
    city: '伊瓜苏',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '参观伊瓜苏大瀑布',
    description: '参观伊瓜苏瀑布景区。',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '' }],
  },
  {
    id: 'spot_br1993_saojose',
    type: 'spot',
    name: '圣若泽',
    latitude: -23.1896,
    longitude: -45.8841,
    country: '巴西',
    province: '圣保罗州',
    city: '圣若泽-杜斯坎普斯',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '1993年巴西国事访问',
    description: '',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '圣若泽' }],
  },
  {
    id: 'spot_br1993_saopaulo',
    type: 'spot',
    name: '圣保罗',
    latitude: -23.5505,
    longitude: -46.6333,
    country: '巴西',
    province: '圣保罗州',
    city: '圣保罗',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '1993年巴西国事访问',
    description: '在圣保罗出席当地安排的欢迎活动。',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '' }],
  },
  {
    id: 'spot_br1993_rio',
    type: 'spot',
    name: '里约热内卢',
    latitude: -22.9068,
    longitude: -43.1729,
    country: '巴西',
    province: '里约热内卢州',
    city: '里约热内卢',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '1993年巴西国事访问',
    description: '在里约热内卢出席相关活动。',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '' }],
  },
  {
    id: 'spot_br1993_manaus',
    type: 'spot',
    name: '马瑙斯',
    latitude: -3.119,
    longitude: -60.0217,
    country: '巴西',
    province: '亚马孙州',
    city: '马瑙斯',
    date: '1993-11-22',
    endDate: '1993-11-28',
    title: '1993年巴西国事访问',
    description: '',
    tags: ['1993巴西国事访问'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '维基百科：江泽民外事访问列表', note: '' }],
  },
  {
    id: 'spot_1984_gy_main',
    type: 'spot',
    name: '四川广元',
    latitude: 32.4355,
    longitude: 105.8438,
    country: '中国',
    province: '四川省',
    city: '广元市',
    date: '1984-06-09',
    title: '1984年视察广元',
    description: '',
    tripSummary:
      '1984年6月9日，电子工业部江部长来到四川省广元市原081基地视察，欣然为已更名为「广明无线电厂」的原120厂题写了厂名。在召开的大会上，他说：「广元地区是电子工业重点基地之一，对全国、全省电子工业的发展起了重要的作用。零八一总厂家大业大，又兼地处交通要道，应立足于就地发展。」他最后高兴地说：「广元是个好地方，是武则天的出生地，人杰地灵，我们来到这里精神焕发。」下午，前往皇泽寺和千佛崖参观。',
    tags: ['1984广元视察'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '地方志及口述史料', note: '1984年6月9日' }],
  },
  {
    id: 'spot_1984_gy_081',
    type: 'spot',
    name: '零八一分基地',
    latitude: 32.426,
    longitude: 105.872,
    country: '中国',
    province: '四川省',
    city: '广元市',
    date: '1984-06-09',
    title: '视察081基地',
    description: '视察原081基地，并在当地召开大会发表讲话。',
    tags: ['1984广元视察'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '地方志及口述史料', note: '原081基地' }],
  },
  {
    id: 'inscription_1984_gy_guangming',
    type: 'inscription',
    name: '广明无线电厂',
    latitude: 32.428,
    longitude: 105.874,
    country: '中国',
    province: '四川省',
    city: '广元市',
    date: '1984-06-09',
    title: '题写厂名',
    description: '欣然为已更名为「广明无线电厂」的原120厂题写厂名。',
    tags: ['1984广元视察'],
    color: '#F57F17',
    icon: '✒️',
    images: [],
    sources: [{ title: '地方志及口述史料', note: '原120厂' }],
  },
  {
    id: 'spot_1984_gy_huangze',
    type: 'spot',
    name: '皇泽寺',
    latitude: 32.4411,
    longitude: 105.8603,
    country: '中国',
    province: '四川省',
    city: '广元市',
    date: '1984-06-09',
    title: '下午参观',
    description: '下午前往皇泽寺参观。',
    tags: ['1984广元视察'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '地方志及口述史料', note: '' }],
  },
  {
    id: 'spot_1984_gy_qianfo',
    type: 'spot',
    name: '千佛崖',
    latitude: 32.3917,
    longitude: 105.8778,
    country: '中国',
    province: '四川省',
    city: '广元市',
    date: '1984-06-09',
    title: '下午参观',
    description: '下午前往千佛崖参观。',
    tags: ['1984广元视察'],
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '地方志及口述史料', note: '' }],
  },
  {
    id: 'spot_1984_chengdu_school',
    type: 'spot',
    name: '成都无线电机械学校',
    latitude: 30.6824,
    longitude: 104.043,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '1984-06-02',
    title: '视察指导工作',
    description:
      '电子工业部江部长到四川省成都无线电机械学校（今成都工业学院）视察指导工作，听取了校长孙茂营（右）、校党委书记李德胜（左）的工作汇报。',
    tags: ['1984成都成无校视察'],
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '1984年视察现场',
        title: '听取工作汇报',
        description: '孙茂营（右）、李德胜（左）向江部长汇报工作。',
        data: '/markers/spot-1984-chengdu-school.png',
      },
    ],
    sources: [{ title: '校史资料', note: '1984年6月2日' }],
  },
  {
    id: 'inscription_2004_dadu_memorial',
    type: 'inscription',
    name: '中国工农红军强渡大渡河纪念馆',
    latitude: 29.2458,
    longitude: 102.2369,
    country: '中国',
    province: '四川省',
    city: '雅安市',
    date: '2004-05-24',
    title: '馆名题字',
    description:
      '中国工农红军强渡大渡河纪念馆在四川省雅安市石棉县安顺乡安顺村正式建成开馆，馆名由江泽民同志题写。',
    color: '#F57F17',
    icon: '✒️',
    images: [
      {
        name: '馆名牌匾',
        title: '中国工农红军强渡大渡河纪念馆',
        description: '开馆当日悬挂的题字牌匾。',
        data: '/markers/inscription-2004-dadu-memorial.png',
      },
    ],
    sources: [{ title: '纪念馆公开资料', note: '石棉县安顺乡安顺村' }],
  },
  {
    id: 'spot_2002_wenjiang_tashui',
    type: 'spot',
    name: '温江区踏水镇',
    latitude: 30.845,
    longitude: 103.825,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '2002-05-20',
    title: '视察温江',
    description:
      '来到成都市温江区踏水镇视察，先后参观成都海峡两岸科技产业开发园区内的四川际天时股份有限公司和易园苗木基地。对温江的经济和花木产业发展情况非常满意，对「三个代表」重要思想学习教育活动所取得的成绩给予充分肯定。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '踏水镇视察',
        title: '视察温江',
        description: '在温江区踏水镇及海峡两岸科技产业开发园区视察期间。',
        data: '/markers/2002-wenjiang-tashui.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月20日上午' }],
  },
  {
    id: 'inscription_2002_wenjiang_tashui',
    type: 'inscription',
    name: '温江区踏水镇',
    latitude: 30.845,
    longitude: 103.825,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '2002-05-20',
    title: '于温江区踏水镇',
    description: '视察期间题写「于温江区踏水镇」。',
    color: '#F57F17',
    icon: '✒️',
    images: [
      {
        name: '题字',
        title: '于温江区踏水镇',
        description: '江泽民，二〇〇二年五月二十日。',
        data: '/markers/2002-wenjiang-tashui.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月20日' }],
  },
  {
    id: 'spot_2002_zipingpu',
    type: 'spot',
    name: '四川紫坪铺水利枢纽',
    latitude: 31.018,
    longitude: 103.582,
    country: '中国',
    province: '四川省',
    city: '都江堰市',
    date: '2002-05-20',
    title: '视察紫坪铺工地',
    description:
      '下午来到水利水电第十二工程局有限公司在建工程四川紫坪铺水利枢纽建设工地视察，与都江堰市委书记张宁生亲切握手，亲切看望工程建设者，听取项目情况并观看工程图文展版。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '与张宁生握手',
        title: '视察紫坪铺工地',
        description: '与都江堰市委书记张宁生亲切握手。',
        data: '/markers/2002-zipingpu-handshake.png',
      },
      {
        name: '观看工程展版',
        title: '视察紫坪铺工地',
        description: '观看紫坪铺水利枢纽工程图文展版。',
        data: '/markers/2002-zipingpu-site.png',
      },
      {
        name: '看望工程建设者',
        title: '视察紫坪铺工地',
        description: '亲切看望工程建设者并讲话。',
        data: '/markers/2002-zipingpu-workers.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月20日下午' }],
  },
  {
    id: 'spot_2002_chengdu_dufu',
    type: 'spot',
    name: '杜甫草堂',
    latitude: 30.6603,
    longitude: 104.0252,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '2002-05-21',
    title: '参观杜甫草堂',
    description: '江同志来到四川省成都市杜甫草堂参观。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '草堂内参观',
        title: '参观杜甫草堂',
        description: '在草堂内参观杜甫塑像及相关陈列。',
        data: '/markers/2002-chengdu-dufu-interior.png',
      },
      {
        name: '草堂前',
        title: '草堂',
        description: '在草堂标志性「草堂」题字景观前。',
        data: '/markers/2002-chengdu-dufu-caotang.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月21日上午' }],
  },
  {
    id: 'spot_2002_chengdu_htzone',
    type: 'spot',
    name: '成都高新技术产业开发区',
    latitude: 30.592,
    longitude: 104.066,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '2002-05-21',
    title: '视察高新区',
    description:
      '下午视察成都高新技术产业开发区留学人员创业园、博士创业园和地奥集团、国腾集团。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '视察企业',
        title: '视察高新区',
        description: '下午视察留学人员创业园及相关企业期间。',
        data: '/markers/2002-chengdu-htzone.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月21日下午' }],
  },
  {
    id: 'inscription_2002_chengdu_jinniu',
    type: 'inscription',
    name: '金牛宾馆',
    latitude: 30.6895,
    longitude: 104.052,
    country: '中国',
    province: '四川省',
    city: '成都市',
    date: '2002-05-21',
    title: '重到金牛宾馆',
    description: '晚上一行下榻金牛宾馆，题写「重到金牛宾馆」。',
    color: '#F57F17',
    icon: '✒️',
    images: [
      {
        name: '题字',
        title: '重到金牛宾馆',
        description: '江泽民，二〇〇二年五月廿一日。',
        data: '/markers/2002-chengdu-jinniu-inscription.png',
      },
    ],
    sources: [{ title: '公开报道', note: '2002年5月21日晚' }],
  },
  {
    id: 'spot_1986_children_day_sh',
    type: 'spot',
    name: '中国福利会少年宫',
    latitude: 31.2203,
    longitude: 121.4368,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1986-06-01',
    title: '六一儿童节活动',
    description:
      '江市长来到上海中国福利会少年宫参加六一儿童节活动，少先队员为他系上红领巾。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '系红领巾',
        title: '六一儿童节活动',
        description: '少先队员为江市长系上红领巾。',
        data: '/markers/1986-children-day-shanghai-scarf.png',
      },
    ],
    sources: [{ title: '公开报道', note: '延安西路64号·少年宫' }],
  },
  {
    id: 'spot_1987_children_day_sh',
    type: 'spot',
    name: '中国福利会少年宫',
    latitude: 31.2203,
    longitude: 121.4368,
    country: '中国',
    province: '上海市',
    city: '',
    date: '1987-06-01',
    title: '六一儿童节活动',
    description: '江市长来到上海中国福利会少年宫参加六一儿童节活动。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '与少年儿童在一起',
        title: '六一儿童节活动',
        description: '参加六一儿童节庆祝活动，与少年儿童亲切互动。',
        data: '/markers/1987-children-day-shanghai.png',
      },
    ],
    sources: [{ title: '公开报道', note: '延安西路64号·少年宫' }],
  },
  {
    id: 'spot_1990_children_day_bj',
    type: 'spot',
    name: '北京',
    latitude: 39.9042,
    longitude: 116.4074,
    country: '中国',
    province: '北京市',
    city: '',
    date: '1990-06-01',
    title: '庆祝六一儿童节',
    description: '江同志在北京与少年儿童共同庆祝六一国际儿童节。',
    color: '#1E88E5',
    icon: '📍',
    images: [
      {
        name: '庆祝活动',
        title: '庆祝六一儿童节',
        description: '佩戴红领巾，与少年儿童一起参加活动。',
        data: '/markers/1990-children-day-beijing-1.png',
      },
      {
        name: '与少年儿童在一起',
        title: '庆祝六一儿童节',
        description: '在庆祝活动中与少年儿童亲切互动。',
        data: '/markers/1990-children-day-beijing-2.png',
      },
      {
        name: '活动现场',
        title: '庆祝六一儿童节',
        description: '六一国际儿童节庆祝活动现场。',
        data: '/markers/1990-children-day-beijing-3.png',
      },
    ],
    sources: [{ title: '公开报道', note: '1990年6月1日·北京' }],
  },
  ...ITINERARY_MARKERS,
];

/** 已从示例库撤下的标点 ID（版本迁移时从 localStorage 同步删除） */
export const REMOVED_MARKER_IDS = ['spot_trip_001', 'event_trip_001'];

// 数据版本：条数变更或结构迁移时递增（32 = 1990–1996 外事行程批量添加）
export const DATA_VERSION = 32;

export const SAMPLE_MARKERS = isPortfolioDemoData() ? PORTFOLIO_SAMPLE_MARKERS : SAMPLE_MARKERS_RAW;
