export const MARKER_TYPES = {
  spot: {
    key: 'spot',
    label: '足迹',
    labelEn: 'Footprint',
    color: '#1E88E5',
    icon: '📍',
    description: '出生地、工作地、访问地点',
  },
  event: {
    key: 'event',
    label: '历史事件',
    labelEn: 'Event',
    color: '#D32F2F',
    icon: '⭐',
    description: '重要历史时刻',
  },
  inscription: {
    key: 'inscription',
    label: '题字',
    labelEn: 'Inscription',
    color: '#F57F17',
    icon: '✒️',
    description: '书法题字地点',
  },
};

export const STORAGE_KEY = 'jzm_memorial_markers';

export const DEFAULT_CENTER = [35.8617, 104.1954];
export const DEFAULT_ZOOM = 4;

export const SAMPLE_MARKERS = [
  {
    id: 'spot_001',
    type: 'spot',
    name: '江苏扬州',
    latitude: 32.4007,
    longitude: 119.4139,
    date: '1926-08-17',
    title: '出生地',
    description: '江泽民同志于1926年8月17日出生于江苏省扬州市',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方履历', note: '' }],
  },
  {
    id: 'spot_002',
    type: 'spot',
    name: '上海',
    latitude: 31.2304,
    longitude: 121.4737,
    date: '1989-04',
    title: '上海市委书记任所',
    description: '1989年4月至1989年6月任上海市委书记，此后开始新阶段',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '官方履历', note: '' }],
  },
  {
    id: 'spot_003',
    type: 'spot',
    name: '北京',
    latitude: 39.9042,
    longitude: 116.4074,
    date: '1989-06',
    title: '中央工作地',
    description: '调任中央后长期在北京工作，主持中央工作',
    color: '#1E88E5',
    icon: '📍',
    images: [],
    sources: [{ title: '新华社档案', note: '' }],
  },
  {
    id: 'event_001',
    type: 'event',
    name: '调任中央',
    latitude: 39.9042,
    longitude: 116.3974,
    date: '1989-05-31',
    title: '重要历史转折点',
    description: '从上海调任中央，开始新的历史阶段',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '新华社档案', note: '' }],
  },
  {
    id: 'event_002',
    type: 'event',
    name: '十三届四中全会',
    latitude: 39.9142,
    longitude: 116.3774,
    date: '1989-06-09',
    title: '十三届四中全会',
    description: '中国共产党第十三届中央委员会第四次全体会议',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '党史资料', note: '' }],
  },
  {
    id: 'event_003',
    type: 'event',
    name: '南方谈话地',
    latitude: 22.5431,
    longitude: 114.0579,
    date: '1992-01-18',
    title: '南方视察',
    description: '1992年南方视察，发表重要讲话，推动改革开放深入发展',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '人民日报档案', note: '' }],
  },
  {
    id: 'event_004',
    type: 'event',
    name: '澳门回归',
    latitude: 22.1987,
    longitude: 113.5439,
    date: '1999-12-20',
    title: '澳门回归祖国',
    description: '1999年12月20日，澳门回归祖国，见证历史时刻',
    color: '#D32F2F',
    icon: '⭐',
    images: [],
    sources: [{ title: '新华社', note: '' }],
  },
  {
    id: 'inscription_001',
    type: 'inscription',
    name: '虎门大桥',
    latitude: 22.7851,
    longitude: 113.6307,
    date: '1997-06-09',
    title: '虎门大桥题字',
    description: '虎门大桥落成时，江泽民同志亲自题字',
    color: '#F57F17',
    icon: '✒️',
    images: [],
    sources: [{ title: '虎门大桥资料', note: '' }],
  },
];
